coinFragment:
    name: "§bFragment ancien"
    lore:
      - "§f➥ §eLes fragments anciens"
      - "§f➥ §es'échangent contre"
      - "§f➥ §edes pièces antiques"
      - ""
      - "§f⦁ §bRareté §f» §d✯"
coin:
    name: "§bPièce antique"
    lore:
      - "§f➥ §eLes pièces d'or"
      - "§f➥ §es'échangent contre"
      - "§f➥ §edes items spéciaux"
      - ""
      - "§f⦁ §bRareté §f» §d✯✯"